version: '3.8'
services:
  zoplanner:
    build: .
    container_name: zoplanner
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - zoplanner-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  zoplanner-data: