name: CI - Build and Test Java

on:
  push:
    branches: [ CI-build-test ]
  pull_request:
    branches: [ CI-build-test ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: zoplanner_user
          POSTGRES_PASSWORD: zoplanner_password
          POSTGRES_DB: zoplanner
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      HOST: localhost
      PORT: 5432
      POSTGRES_USER: zoplanner_user
      POSTGRES_PASSWORD: zoplanner_password

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # build and test will fail workflow if tests fail
      - name: Build and Test with Maven
        run: mvn clean verify
        working-directory: ./webapi

      # publish test results even if test fails
      - name: Publish test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: webapi/target/surefire-reports

      # show build success if all tests passed
      - name: Display test results
        if: success()
        run: echo "Build and all tests passed!"
