spring.application.name=webapi

# Databasanslutning med standardvärden
spring.datasource.url=jdbc:postgresql://${HOST:localhost}:${PORT:5432}/zoplanner
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:test123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate-inställningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Visa SQL-frågor (utvecklingsläge)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger beskrivning på http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.info.title="zoplanner-api (Java)"
springdoc.api-docs.info.description="Java CRUD API connecting to PostgreSQL database."
springdoc.api-docs.info.version=v1
