spring.application.name=webapi

# Databasanslutning med standardvärden
spring.datasource.url=jdbc:postgresql://${HOST:localhost}:${PORT:5432}/zoplanner
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:test123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate-inställningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Visa SQL-frågor (utvecklingsläge)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
