spring.application.name=webapi

# Databasanslutning
spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/zoplanner
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate-installningar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Visa SQL-frï¿½gor (utvecklingsläge)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true